/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.ProductoVendido;
import modelo.VentaDAO;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.ProductoVendido;
import modelo.ReporteMasVendidos;
/**
 *
 * @author jeremy
 */
public class FormReporteMasVendidos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormReporteMasVendidos.class.getName());
    private final VentaDAO ventaDAO = new VentaDAO();
    /**
     * Creates new form FormReporteMasVendidos
     */
    public FormReporteMasVendidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMasVendido = new javax.swing.JLabel();
        lblUnidadesMasVendido = new javax.swing.JLabel();
        cbxTop = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMasVendidos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel1.setText("Productos mas vendidos");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jLabel2.setText("Ordenados por unidades vendidas");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jLabel3.setText("Producto mas vendido");

        lblMasVendido.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        lblMasVendido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMasVendido.setText("...");

        lblUnidadesMasVendido.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        lblUnidadesMasVendido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnidadesMasVendido.setText("...");

        cbxTop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOP 5", "TOP 10", "TODOS" }));
        cbxTop.addActionListener(this::cbxTopActionPerformed);

        jLabel6.setText("Mostrar");

        tablaMasVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Codigo", "Nombre", "Unidades", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMasVendidos);
        if (tablaMasVendidos.getColumnModel().getColumnCount() > 0) {
            tablaMasVendidos.getColumnModel().getColumn(0).setResizable(false);
            tablaMasVendidos.getColumnModel().getColumn(1).setResizable(false);
            tablaMasVendidos.getColumnModel().getColumn(2).setResizable(false);
            tablaMasVendidos.getColumnModel().getColumn(3).setResizable(false);
            tablaMasVendidos.getColumnModel().getColumn(4).setResizable(false);
        }

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(this::btnImprimirActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUnidadesMasVendido)
                                    .addComponent(lblMasVendido)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMasVendido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUnidadesMasVendido)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnCerrar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTopActionPerformed
        cargarDatos();

        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTopActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarDatos();
    

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
         dispose();   

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        List<ProductoVendido> lista = ventaDAO.obtenerMasVendidos(obtenerLimite());

if (lista.isEmpty()) {
    JOptionPane.showMessageDialog(this, "No hay ventas registradas para imprimir.",
            "Sin datos", JOptionPane.WARNING_MESSAGE);
    return;
}

String criterio = String.valueOf(cbxTop.getSelectedItem());

JFileChooser chooser = new JFileChooser();
chooser.setDialogTitle("Guardar reporte de más vendidos");
chooser.setFileFilter(new FileNameExtensionFilter("Archivo de texto (*.txt)", "txt"));
String nombreSugerido = "reporte_mas_vendidos_"
        + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmm")) + ".txt";
chooser.setSelectedFile(new File(nombreSugerido));

if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
    return;
}

File archivo = chooser.getSelectedFile();
if (!archivo.getName().toLowerCase().endsWith(".txt")) {
    archivo = new File(archivo.getParentFile(), archivo.getName() + ".txt");
}

if (archivo.exists()) {
    int r = JOptionPane.showConfirmDialog(this,
            "El archivo ya existe. ¿Deseas reemplazarlo?",
            "Confirmar", JOptionPane.YES_NO_OPTION);
    if (r != JOptionPane.YES_OPTION) {
        return;
    }
}

try {
    new ReporteMasVendidos(lista, criterio).guardar(archivo);
    JOptionPane.showMessageDialog(this, "Reporte guardado en:\n" + archivo.getAbsolutePath(),
            "Éxito", JOptionPane.INFORMATION_MESSAGE);
} catch (IOException ex) {
    JOptionPane.showMessageDialog(this, "No se pudo guardar el archivo:\n" + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormReporteMasVendidos().setVisible(true));
    }
    
    
        private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new String[] {"#", "Código", "Nombre", "Unidades", "Monto (S/)"}, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        tablaMasVendidos.setModel(modelo);
    }

    private int obtenerLimite() {
        String seleccion = cbxTop.getSelectedItem().toString();
        if (seleccion.equals("Top 5")) {
            return 5;
        }
        if (seleccion.equals("Top 10")) {
            return 10;
        }
        return 0; // "Todos"
    }

    private void cargarDatos() {
        List<ProductoVendido> lista = ventaDAO.obtenerMasVendidos(obtenerLimite());

        DefaultTableModel modelo = (DefaultTableModel) tablaMasVendidos.getModel();
        modelo.setRowCount(0);

        int puesto = 1;
        for (ProductoVendido p : lista) {
            modelo.addRow(new Object[] {
                puesto++,
                p.getCodigo(),
                p.getNombre(),
                p.getUnidades(),
                String.format("%.2f", p.getMonto())
            });
        }

        if (lista.isEmpty()) {
            lblMasVendido.setText("Sin ventas");
            lblUnidadesMasVendido.setText("-");
        } else {
            ProductoVendido top = lista.get(0);
            lblMasVendido.setText(top.getNombre());
            lblUnidadesMasVendido.setText(top.getUnidades() + " unidades vendidas");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> cbxTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMasVendido;
    private javax.swing.JLabel lblUnidadesMasVendido;
    private javax.swing.JTable tablaMasVendidos;
    // End of variables declaration//GEN-END:variables
}
