/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import javax.swing.JOptionPane;
import modelo.Producto;
import modelo.ProductoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jeremy
 */
public class FormProductos extends javax.swing.JFrame {
    
    // Lista en memoria para ir acumulando los productos antes de ir a la BD
    private java.util.List<Producto> listaTemporal = new java.util.ArrayList<>();
    private ProductoDAO productoDAO = new ProductoDAO();
    private int contadorCodigo = 1; // Para generar P-001, P-002, etc.

    public FormProductos() {
        initComponents();
        txtCodigo.setEditable(false);
        
        // Limpiar filas por defecto de la JTable
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaProductos.getModel();
        model.setRowCount(0);
        // 2. Obtener el último número registrado en la BD y sumar 1
        int ultimoNumero = productoDAO.obtenerUltimoNumeroCodigo();
        contadorCodigo = ultimoNumero + 1; // Si el último era 2, ahora será 3
        mostrarSiguienteCodigo();
    }
  
    private void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        txtSocketPuerto.setText("");
        txtAniosGarantia.setText("");
        cbxCategoria.setSelectedIndex(0);
        actualizarVisibilidadCampos();
        txtCodigo.requestFocus();
    
}
    
    // Método para mostrar el código autogenerado en el txtCodigo
    private void mostrarSiguienteCodigo() {
        txtCodigo.setText(String.format("P-%03d", contadorCodigo));
    }
    
  private void actualizarVisibilidadCampos() {
    String categoria = (String) cbxCategoria.getSelectedItem();

    if ("Todos".equalsIgnoreCase(categoria)) {
        // Habilita ambos campos
        txtSocketPuerto.setEnabled(true);
        txtAniosGarantia.setEnabled(true);
    } else if ("Pieza".equalsIgnoreCase(categoria)) {
        // Solo habilita Socket / Puerto
        txtSocketPuerto.setEnabled(true);
        txtAniosGarantia.setEnabled(false);
        txtAniosGarantia.setText("");
    } else if ("Equipo".equalsIgnoreCase(categoria)) {
        // Solo habilita Años de Garantía
        txtSocketPuerto.setEnabled(false);
        txtSocketPuerto.setText("");
        txtAniosGarantia.setEnabled(true);
    }
}
    private void mostrarEnTabla(List<Producto> lista) {
    DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
    modelo.setRowCount(0); // borra las filas anteriores (incluidas las 4 vacías del diseñador)

    for (Producto p : lista) {
        modelo.addRow(new Object[] {
            p.getCodigo(),
            p.getNombre(),
            p.getCantidad(),
            p.getPrecio()
        });
        }
    }

    private void cargarTabla() {
        mostrarEnTabla(productoDAO.listar());
    }
    
    private void recalcularCodigos() {
    // Obtener la base inicial según lo que ya existe guardado en la BD MySQL
    int baseCodigo = productoDAO.obtenerUltimoNumeroCodigo();

    // 1. Recorrer la lista en memoria y reasignar correlativamente los códigos
    for (int i = 0; i < listaTemporal.size(); i++) {
        int nuevoNumero = baseCodigo + 1 + i;
        String nuevoCodigo = String.format("P-%03d", nuevoNumero);
        listaTemporal.get(i).setCodigo(nuevoCodigo);
    }

    // 2. Ajustar el contador para el siguiente elemento que el usuario vaya a registrar
    contadorCodigo = baseCodigo + 1 + listaTemporal.size();
    mostrarSiguienteCodigo();

    // 3. Refrescar los datos mostrados en la JTable
    DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
    model.setRowCount(0); // Limpiar vista de la tabla

    for (Producto p : listaTemporal) {
        model.addRow(new Object[]{
            p.getCodigo(),
            p.getNombre(),
            p.getCantidad(),
            p.getPrecio()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtSocketPuerto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAniosGarantia = new javax.swing.JTextField();
        btnGuardarLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtCodigo.setEditable(false);
        txtCodigo.setEnabled(false);

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Ingreso de productos");

        jLabel3.setText("Codigo");

        jLabel4.setText("Nombre");

        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        jLabel5.setText("Precio");

        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProductos);
        if (tablaProductos.getColumnModel().getColumnCount() > 0) {
            tablaProductos.getColumnModel().getColumn(0).setResizable(false);
            tablaProductos.getColumnModel().getColumn(1).setResizable(false);
            tablaProductos.getColumnModel().getColumn(2).setResizable(false);
            tablaProductos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel6.setText("Cantidad");

        btnEliminar.setText("Eliminar Producto");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Pieza", "Equipo" }));
        cbxCategoria.addActionListener(this::cbxCategoriaActionPerformed);

        jLabel1.setText("Categoria");

        jLabel2.setText("Socket / Puerto");

        jLabel7.setText("Años Garantia");

        btnGuardarLista.setText("LISTAR");
        btnGuardarLista.addActionListener(this::btnGuardarListaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAniosGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtSocketPuerto))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel1))
                                            .addGap(36, 36, 36)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSocketPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAniosGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarLista, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (listaTemporal.isEmpty()) {
        JOptionPane.showMessageDialog(this, "La lista está vacía. Agregue productos con el botón LISTAR antes de confirmar.");
        return;
    }

    int guardados = 0;
    int errores = 0;

    // Recorrer la lista en memoria e guardar cada uno en la BD
    for (Producto producto : listaTemporal) {
        if (productoDAO.insertar(producto)) {
            guardados++;
        } else {
            errores++;
        }
    }

    if (errores == 0) {
        JOptionPane.showMessageDialog(this, "¡Éxito! Se guardaron " + guardados + " producto(s) en la base de datos.");
        listaTemporal.clear(); // Se vacía la lista temporal
    } else {
        JOptionPane.showMessageDialog(this, "Se guardaron " + guardados + " producto(s), pero " + errores + " fallaron.");
    }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:
        actualizarVisibilidadCampos();
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void btnGuardarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarListaActionPerformed
        String codigo = txtCodigo.getText().trim(); 
    String nombre = txtNombre.getText().trim();
    String cantidadTxt = txtCantidad.getText().trim();
    String precioTxt = txtPrecio.getText().trim().replace(',', '.');
    String categoria = (String) cbxCategoria.getSelectedItem();

    // Validaciones básicas
    if ("Todos".equalsIgnoreCase(categoria)) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una categoría específica (Pieza o Equipo)");
        return;
    }

    if (nombre.isEmpty() || cantidadTxt.isEmpty() || precioTxt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos principales");
        return;
    }

    int cantidad;
    float precio;
    try {
        cantidad = Integer.parseInt(cantidadTxt);
        precio = Float.parseFloat(precioTxt);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Cantidad y precio deben ser números válidos");
        return;
    }

    // Crear el producto usando el código del txtCodigo (ej: P-001)
    Producto producto = new Producto();
    producto.setCodigo(codigo);
    producto.setNombre(nombre);
    producto.setCategoria(categoria);
    producto.setCantidad(cantidad);
    producto.setPrecio(precio);

    if ("Pieza".equalsIgnoreCase(categoria)) {
        producto.setSocketPuerto(txtSocketPuerto.getText().trim());
    } else if ("Equipo".equalsIgnoreCase(categoria)) {
        try {
            producto.setAniosGarantia(Integer.parseInt(txtAniosGarantia.getText().trim()));
        } catch (NumberFormatException e) {
            producto.setAniosGarantia(0);
        }
    }

    // 1. Guardar SOLO en la lista temporal en memoria
    listaTemporal.add(producto);

    // 2. Mostrar la fila en la JTable
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaProductos.getModel();
    model.addRow(new Object[]{
        producto.getCodigo(),
        producto.getNombre(),
        producto.getCantidad(),
        producto.getPrecio()
    });

    // 3. Incrementar el código autoincremental para el siguiente producto (P-002)
    contadorCodigo++;
    mostrarSiguienteCodigo();

    // 4. Limpiar los campos para un nuevo ingreso
    txtNombre.setText("");
    txtCantidad.setText("");
    txtPrecio.setText("");
    txtSocketPuerto.setText("");
    txtAniosGarantia.setText("");
    cbxCategoria.setSelectedIndex(0);
    }//GEN-LAST:event_btnGuardarListaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        // Obtener el índice de la fila seleccionada en la tabla
        int filaSeleccionada = tablaProductos.getSelectedRow();

        if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto de la lista para eliminar.");
        return;
        }

        // Confirmar eliminación
        int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Está seguro de eliminar este producto de la lista temporal?", 
        "Confirmar Eliminación", 
        JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
        // 1. Remover de la lista temporal en memoria
        listaTemporal.remove(filaSeleccionada);

        // 2. Recalcular correlativos y actualizar la JTable
        recalcularCodigos();

        JOptionPane.showMessageDialog(this, "Producto eliminado y correlativo actualizado.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    /* Crear y mostrar el formulario */
    java.awt.EventQueue.invokeLater(() -> {
        new FormProductos().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarLista;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtAniosGarantia;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSocketPuerto;
    // End of variables declaration//GEN-END:variables
}
