/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author jeremy
 */
public class FormMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMain.class.getName());

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        menuMain = new javax.swing.JMenuBar();
        menuProductos = new javax.swing.JMenu();
        jMenuProducto1 = new javax.swing.JMenuItem();
        jMenuProducto2 = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenu();
        jMenuListado = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        jMenuRegistroVenta = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        jMenuListadoVenta = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computel/Icono.png"))); // NOI18N
        lblIcono.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblIcono.setMaximumSize(new java.awt.Dimension(1008, 268));

        menuProductos.setText("Productos");
        menuProductos.setAlignmentX(1.0F);
        menuProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProductosMouseClicked(evt);
            }
        });

        jMenuProducto1.setText("Registrar Producto");
        jMenuProducto1.addActionListener(this::jMenuProducto1ActionPerformed);
        menuProductos.add(jMenuProducto1);

        jMenuProducto2.setText("Registrar Pieza y Equipo");
        jMenuProducto2.addActionListener(this::jMenuProducto2ActionPerformed);
        menuProductos.add(jMenuProducto2);

        menuMain.add(menuProductos);

        menuInventario.setText("Inventarios");
        menuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInventarioMouseClicked(evt);
            }
        });

        jMenuListado.setText("Listado de Productos");
        jMenuListado.addActionListener(this::jMenuListadoActionPerformed);
        menuInventario.add(jMenuListado);

        menuMain.add(menuInventario);

        menuVentas.setText("Ventas");

        jMenuRegistroVenta.setText("REGISTRO DE VENTA");
        jMenuRegistroVenta.addActionListener(this::jMenuRegistroVentaActionPerformed);
        menuVentas.add(jMenuRegistroVenta);

        menuMain.add(menuVentas);

        menuReportes.setText("Reportes");
        menuReportes.addActionListener(this::menuReportesActionPerformed);

        jMenuListadoVenta.setText("LISTADO DE VENTA");
        jMenuListadoVenta.addActionListener(this::jMenuListadoVentaActionPerformed);
        menuReportes.add(jMenuListadoVenta);

        jMenuItem1.setText("REPORTE BAJO STOCK");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        menuReportes.add(jMenuItem1);

        jMenuItem2.setText("REPORTE DE MAS VENDIDOS");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        menuReportes.add(jMenuItem2);

        menuMain.add(menuReportes);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductosMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_menuProductosMouseClicked

    private void menuInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInventarioMouseClicked
        
       
        // TODO add your handling code here:
    }//GEN-LAST:event_menuInventarioMouseClicked

    private void jMenuProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProducto1ActionPerformed
        // TODO add your handling code here:
       abrirBloqueando(new FormProducto());
        
    }//GEN-LAST:event_jMenuProducto1ActionPerformed

    private void jMenuProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProducto2ActionPerformed
        // TODO add your handling code here:
        abrirBloqueando(new FormProductos());
    }//GEN-LAST:event_jMenuProducto2ActionPerformed

    private void jMenuListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListadoActionPerformed
        // TODO add your handling code here:
         abrirBloqueando(new FormInventarios());
    }//GEN-LAST:event_jMenuListadoActionPerformed

    private void jMenuRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistroVentaActionPerformed
        // TODO add your handling code here:
         abrirBloqueando(new FormVentas());
    }//GEN-LAST:event_jMenuRegistroVentaActionPerformed

    private void jMenuListadoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListadoVentaActionPerformed
        // TODO add your handling code here:
        abrirBloqueando(new FormListadoVentas());
        
    }//GEN-LAST:event_jMenuListadoVentaActionPerformed

    private void menuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReportesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        abrirBloqueando(new FormReporteBajoStock());
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        abrirBloqueando(new FormReporteMasVendidos());

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMain().setVisible(true));
    }
    
    private void abrirBloqueando(javax.swing.JFrame ventana) {
    this.setEnabled(false); // bloquea FormMain
    ventana.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            FormMain.this.setEnabled(true);
            FormMain.this.toFront();
        }
    });
    ventana.setVisible(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuListado;
    private javax.swing.JMenuItem jMenuListadoVenta;
    private javax.swing.JMenuItem jMenuProducto1;
    private javax.swing.JMenuItem jMenuProducto2;
    private javax.swing.JMenuItem jMenuRegistroVenta;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuVentas;
    // End of variables declaration//GEN-END:variables
}
