/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DetalleVenta;
import modelo.Producto;
import modelo.ProductoDAO;
import modelo.Venta;
import modelo.VentaDAO;

/**
 *
 * @author jeremy
 */
public class FormVentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormVentas.class.getName());
    
    private ProductoDAO productoDAO = new ProductoDAO();
    // Tasa de IGV al 5%
    private static final float TASA_IGV = 0.05f;
    
    // Listas para manejar el estado en memoria sin tocar la BD
    private List<Producto> listaProductosLocal = new ArrayList<>();
    private List<DetalleVenta> listaCarrito = new ArrayList<>();
    /**
     * Creates new form FormVentas
     */
    public FormVentas() {
    initComponents();
    txtCantidadCarrito.setEnabled(true);
    txtCantidadCarrito.setEditable(true);
    cargarProductosDesdeBD();
}

    private void cargarProductosDesdeBD() {
    // 1. Traer los productos reales de la BD solo una vez
    listaProductosLocal = productoDAO.buscarOFiltrar("", "Todo"); // O usar buscarOFiltrar("", "Todo")

    // 2. Renderizar la tabla de la izquierda (Stock Actual)
    actualizarTablaStockActual();
}
    private void actualizarTablaStockActual() {
    DefaultTableModel model = (DefaultTableModel) tblStockActual.getModel(); // Nombre de tu tabla izquierda
    model.setRowCount(0);

    for (Producto p : listaProductosLocal) {
        model.addRow(new Object[]{
            p.getCodigo(),
            p.getNombre(),
            p.getCantidad(), // Muestra la cantidad local disponible
            String.format("%.2f", p.getPrecio())
        });
    }
}
    private void calcularTotalesCarrito() {
    float subtotal = 0.0f;

    for (DetalleVenta det : listaCarrito) {
        subtotal += (det.getCantidad() * det.getPrecioUnitario());
    }

    float igv = subtotal * TASA_IGV;
    float total = subtotal + igv;

    // Asignar los montos con formato decimal
    txtSubtotal.setText(String.format("S/ %.2f", subtotal));
    txtIGV.setText(String.format("S/ %.2f", igv));
    txtTotal.setText(String.format("S/ %.2f", total));
}
    
    private void actualizarTablaCarrito() {
    DefaultTableModel model = (DefaultTableModel) tblCarrito.getModel(); // Nombre de tu tabla derecha
    model.setRowCount(0);

    for (DetalleVenta det : listaCarrito) {
        model.addRow(new Object[]{
            det.getCodigoProducto(),
            det.getNombreProducto(),
            det.getCantidad(),
            String.format("%.2f", det.getPrecioUnitario())
        });
    }
}
    
    
    private void tblCarritoMouseClicked(java.awt.event.MouseEvent evt) {                                        
    int filaSel = tblCarrito.getSelectedRow();
    if (filaSel != -1) {
        // Habilitar la caja de texto del carrito
        txtCantidadCarrito.setEnabled(true);
        txtCantidadCarrito.setEditable(true);
        
        // Obtener la cantidad de la fila seleccionada
        Object valorCantidad = tblCarrito.getValueAt(filaSel, 2);
        txtCantidadCarrito.setText(String.valueOf(valorCantidad));
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCarrito = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        tableStock = new javax.swing.JScrollPane();
        tblStockActual = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadCarrito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIGV = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnConfirmarVenta = new javax.swing.JButton();
        btnEliminarItem = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCarrito.setViewportView(tblCarrito);

        tblStockActual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableStock.setViewportView(tblStockActual);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        jLabel1.setText("Cantidad");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel2.setText("Registro de Ventas");

        jLabel3.setText("Stock Actual");

        txtCantidadCarrito.addActionListener(this::txtCantidadCarritoActionPerformed);

        jLabel4.setText("Cantidad");

        jLabel5.setText("Subtotal:");

        jLabel6.setText("IGV:");

        jLabel7.setText("Total:");

        txtIGV.setEditable(false);
        txtIGV.setEnabled(false);

        txtSubtotal.setEditable(false);
        txtSubtotal.setEnabled(false);

        txtTotal.setEditable(false);
        txtTotal.setEnabled(false);

        btnConfirmarVenta.setText("Confirmar Venta");
        btnConfirmarVenta.addActionListener(this::btnConfirmarVentaActionPerformed);

        btnEliminarItem.setText("Eliminar item");
        btnEliminarItem.addActionListener(this::btnEliminarItemActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jLabel8.setText("Carrito de Compras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tableStock, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCantidadCarrito))
                                .addComponent(tableCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminarItem)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tableCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tableStock, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidadCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarItem)
                            .addComponent(btnEditar)
                            .addComponent(btnLimpiar))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCarritoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        // 1. Validar que haya una fila seleccionada en la tabla Stock Actual
    int filaSeleccionada = tblStockActual.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla Stock Actual.", "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Validar que la cantidad ingresada sea un número entero válido
    int cantidadAAgregar = 0;
    try {
        String textoCantidad = txtCantidad.getText().trim(); // El JTextField debajo de Stock Actual
        if (textoCantidad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la cantidad a agregar.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        cantidadAAgregar = Integer.parseInt(textoCantidad);
        if (cantidadAAgregar <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese una cantidad numérica entera válida.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. Obtener el producto seleccionado de la lista en memoria
    Producto prodSeleccionado = listaProductosLocal.get(filaSeleccionada);
    int stockDisponible = prodSeleccionado.getCantidad();

    // 4. VALIDACIÓN DE STOCK DISPONIBLE (Ej: Pide 21 pero solo hay 20)
    if (cantidadAAgregar > stockDisponible) {
        JOptionPane.showMessageDialog(this, 
            "Stock insuficiente. Solo quedan " + stockDisponible + " unidades disponibles de este producto.", 
            "Validación de Stock", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 5. RESTAR STOCK LOCALMENTE (En la lista en memoria, NO en BD)
    prodSeleccionado.setCantidad(stockDisponible - cantidadAAgregar);

    // 6. AGREGAR / ACUMULAR EN EL CARRITO DE COMPRAS
    boolean existeEnCarrito = false;
    for (DetalleVenta det : listaCarrito) {
        if (det.getCodigoProducto().equalsIgnoreCase(prodSeleccionado.getCodigo())) {
            det.setCantidad(det.getCantidad() + cantidadAAgregar);
            existeEnCarrito = true;
            break;
        }
    }

    if (!existeEnCarrito) {
        listaCarrito.add(new DetalleVenta(
            prodSeleccionado.getCodigo(),
            prodSeleccionado.getNombre(),
            cantidadAAgregar,
            prodSeleccionado.getPrecio()
        ));
    }

    // REFRESCAR TABLAS Y RECALCULAR OBLIGATORIAMENTE
    actualizarTablaStockActual();
    actualizarTablaCarrito();
    calcularTotalesCarrito(); // <-- ¡ESTA LÍNEA DEBE ESTAR AQUÍ!

    txtCantidadCarrito.setText("");

    // Limpiar el campo de texto
    txtCantidad.setText("");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
       int filaSel = tblCarrito.getSelectedRow();
    if (filaSel == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto del carrito para modificar su cantidad.", "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int cantidadAQuitar = 0;
    try {
        cantidadAQuitar = Integer.parseInt(txtCantidadCarrito.getText().trim());
        if (cantidadAQuitar <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad a quitar debe ser mayor a 0.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 1. Obtener la fila seleccionada del carrito
    DetalleVenta det = listaCarrito.get(filaSel);
    int cantidadActualEnCarrito = det.getCantidad();

    // 2. Validar que no se intente quitar más de lo que hay en el carrito
    if (cantidadAQuitar > cantidadActualEnCarrito) {
        JOptionPane.showMessageDialog(this, 
            "No puede quitar " + cantidadAQuitar + " unidades. Solo hay " + cantidadActualEnCarrito + " en el carrito.", 
            "Cantidad Excedida", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Buscar el producto correspondiente en el stock local
    Producto prodStock = null;
    for (Producto p : listaProductosLocal) {
        if (p.getCodigo().equalsIgnoreCase(det.getCodigoProducto())) {
            prodStock = p;
            break;
        }
    }

    if (prodStock != null) {
        // 4. Sumar la cantidad devuelta al stock local
        prodStock.setCantidad(prodStock.getCantidad() + cantidadAQuitar);

        // 5. Ajustar o eliminar del carrito
        if (cantidadAQuitar == cantidadActualEnCarrito) {
            // Si quita el total exacto (ej. quita 40 de 40), se elimina la fila del carrito
            listaCarrito.remove(filaSel);
        } else {
            // Si quita solo una parte (ej. quita 25 de 40), el carrito queda con la diferencia (15)
            det.setCantidad(cantidadActualEnCarrito - cantidadAQuitar);
        }

        // 6. Refrescar tablas, recalcular totales y mantener el campo habilitado
        actualizarTablaStockActual();
        actualizarTablaCarrito();
        calcularTotalesCarrito();

        txtCantidadCarrito.setText("");
        txtCantidadCarrito.setEnabled(true);
        txtCantidadCarrito.setEditable(true);
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        listaCarrito.clear();
    cargarProductosDesdeBD(); // Recarga los productos iniciales desde la BD
    actualizarTablaCarrito();
    calcularTotalesCarrito();

    txtCantidadCarrito.setText("");
    txtCantidadCarrito.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarItemActionPerformed
        // TODO add your handling code here:
        int filaSel = tblCarrito.getSelectedRow();
    if (filaSel == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto del carrito para eliminar.", "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DetalleVenta det = listaCarrito.get(filaSel);

    // Devolver el stock a la lista local
    for (Producto p : listaProductosLocal) {
        if (p.getCodigo().equalsIgnoreCase(det.getCodigoProducto())) {
            p.setCantidad(p.getCantidad() + det.getCantidad());
            break;
        }
    }

    // Quitar del carrito
    listaCarrito.remove(filaSel);

    actualizarTablaStockActual();
    actualizarTablaCarrito();
    calcularTotalesCarrito();

        txtCantidadCarrito.setText("");
        txtCantidadCarrito.setEnabled(true);
        txtCantidadCarrito.setEditable(true);
    }//GEN-LAST:event_btnEliminarItemActionPerformed

    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
        // TODO add your handling code here:
        if (listaCarrito.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El carrito de compras está vacío.", "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int opcion = JOptionPane.showConfirmDialog(this, "¿Desea confirmar y procesar esta venta?", "Confirmar Venta", JOptionPane.YES_NO_OPTION);
    if (opcion != JOptionPane.YES_OPTION) return;

    // Calcular montos finales
    float subtotal = 0.0f;
    for (DetalleVenta det : listaCarrito) {
        subtotal += (det.getCantidad() * det.getPrecioUnitario());
    }
    float igv = subtotal * TASA_IGV;
    float total = subtotal + igv;

    // Registrar en BD usando VentaDAO
    VentaDAO ventaDAO = new VentaDAO();
    String numFactura = ventaDAO.generarNumeroFactura(); // p.ej. F001-0000001
    
    Venta venta = new Venta(numFactura, new java.util.Date(), subtotal, igv, 0.0f, total);
    venta.setDetalles(listaCarrito);

    if (ventaDAO.registrarVenta(venta)) {
        JOptionPane.showMessageDialog(this, "¡Venta registrada con éxito! Factura: " + numFactura, "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        // Limpiar para una nueva venta
        listaCarrito.clear();
        cargarProductosDesdeBD();
        actualizarTablaCarrito();
        calcularTotalesCarrito();
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardar la venta en la Base de Datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminarItem;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane tableCarrito;
    private javax.swing.JScrollPane tableStock;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTable tblStockActual;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadCarrito;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
